/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MealplanRouteImport } from './routes/mealplan'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegionIdRouteImport } from './routes/region.$id'
import { Route as RecipeIdRouteImport } from './routes/recipe.$id'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BlogIdRouteImport } from './routes/blog.$id'
import { Route as RegionIdDishDishRouteImport } from './routes/region.$id.dish.$dish'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MealplanRoute = MealplanRouteImport.update({
  id: '/mealplan',
  path: '/mealplan',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionIdRoute = RegionIdRouteImport.update({
  id: '/region/$id',
  path: '/region/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeIdRoute = RecipeIdRouteImport.update({
  id: '/recipe/$id',
  path: '/recipe/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionIdDishDishRoute = RegionIdDishDishRouteImport.update({
  id: '/dish/$dish',
  path: '/dish/$dish',
  getParentRoute: () => RegionIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/mealplan': typeof MealplanRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
  '/terms': typeof TermsRoute
  '/blog/$id': typeof BlogIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/profile/edit': typeof ProfileEditRoute
  '/recipe/$id': typeof RecipeIdRoute
  '/region/$id': typeof RegionIdRouteWithChildren
  '/region/$id/dish/$dish': typeof RegionIdDishDishRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/mealplan': typeof MealplanRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
  '/terms': typeof TermsRoute
  '/blog/$id': typeof BlogIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/profile/edit': typeof ProfileEditRoute
  '/recipe/$id': typeof RecipeIdRoute
  '/region/$id': typeof RegionIdRouteWithChildren
  '/region/$id/dish/$dish': typeof RegionIdDishDishRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/mealplan': typeof MealplanRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
  '/terms': typeof TermsRoute
  '/blog/$id': typeof BlogIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/profile/edit': typeof ProfileEditRoute
  '/recipe/$id': typeof RecipeIdRoute
  '/region/$id': typeof RegionIdRouteWithChildren
  '/region/$id/dish/$dish': typeof RegionIdDishDishRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/categories'
    | '/favorites'
    | '/home'
    | '/mealplan'
    | '/notifications'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/search'
    | '/settings'
    | '/shopping'
    | '/terms'
    | '/blog/$id'
    | '/category/$slug'
    | '/profile/edit'
    | '/recipe/$id'
    | '/region/$id'
    | '/region/$id/dish/$dish'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/categories'
    | '/favorites'
    | '/home'
    | '/mealplan'
    | '/notifications'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/search'
    | '/settings'
    | '/shopping'
    | '/terms'
    | '/blog/$id'
    | '/category/$slug'
    | '/profile/edit'
    | '/recipe/$id'
    | '/region/$id'
    | '/region/$id/dish/$dish'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/categories'
    | '/favorites'
    | '/home'
    | '/mealplan'
    | '/notifications'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/search'
    | '/settings'
    | '/shopping'
    | '/terms'
    | '/blog/$id'
    | '/category/$slug'
    | '/profile/edit'
    | '/recipe/$id'
    | '/region/$id'
    | '/region/$id/dish/$dish'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CategoriesRoute: typeof CategoriesRoute
  FavoritesRoute: typeof FavoritesRoute
  HomeRoute: typeof HomeRoute
  MealplanRoute: typeof MealplanRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ShoppingRoute: typeof ShoppingRoute
  TermsRoute: typeof TermsRoute
  BlogIdRoute: typeof BlogIdRoute
  CategorySlugRoute: typeof CategorySlugRoute
  RecipeIdRoute: typeof RecipeIdRoute
  RegionIdRoute: typeof RegionIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mealplan': {
      id: '/mealplan'
      path: '/mealplan'
      fullPath: '/mealplan'
      preLoaderRoute: typeof MealplanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/region/$id': {
      id: '/region/$id'
      path: '/region/$id'
      fullPath: '/region/$id'
      preLoaderRoute: typeof RegionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/$id': {
      id: '/recipe/$id'
      path: '/recipe/$id'
      fullPath: '/recipe/$id'
      preLoaderRoute: typeof RecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/region/$id/dish/$dish': {
      id: '/region/$id/dish/$dish'
      path: '/dish/$dish'
      fullPath: '/region/$id/dish/$dish'
      preLoaderRoute: typeof RegionIdDishDishRouteImport
      parentRoute: typeof RegionIdRoute
    }
  }
}

interface ProfileRouteChildren {
  ProfileEditRoute: typeof ProfileEditRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileEditRoute: ProfileEditRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface RegionIdRouteChildren {
  RegionIdDishDishRoute: typeof RegionIdDishDishRoute
}

const RegionIdRouteChildren: RegionIdRouteChildren = {
  RegionIdDishDishRoute: RegionIdDishDishRoute,
}

const RegionIdRouteWithChildren = RegionIdRoute._addFileChildren(
  RegionIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CategoriesRoute: CategoriesRoute,
  FavoritesRoute: FavoritesRoute,
  HomeRoute: HomeRoute,
  MealplanRoute: MealplanRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRouteWithChildren,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ShoppingRoute: ShoppingRoute,
  TermsRoute: TermsRoute,
  BlogIdRoute: BlogIdRoute,
  CategorySlugRoute: CategorySlugRoute,
  RecipeIdRoute: RecipeIdRoute,
  RegionIdRoute: RegionIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
